# Generated by Django 4.0 on 2022-02-03 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_order_number_alter_order_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_orderd',
            new_name='is_ordered',
        ),
    ]
