# Generated by Django 4.0 on 2022-02-06 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_orderproduct_variation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='orderd',
            new_name='ordered',
        ),
    ]
